### ISSUE TITLE
🐛 Partial data array outputs in wrong columns

### ISSUE THREAD

**Issue by ollyhensby** [maxfordham/xlsxdatagrid#3]
**Issue**
If the data array only contains the partial amount of data (when compared to the properties in the schema), then the data is output to the incorrect column in the xlsx.

**Solution**
Ensure that the data is aligned correctly where it is set. I think this is happening in the `write_table` function.

**Screenshots**
Data with top three lines commented out:
![image](https://github.com/user-attachments/assets/bff797c2-2e20-41cb-acc6-9bb994c2f63b)

Outputs to xlsx to incorrect columns:
![image](https://github.com/user-attachments/assets/ebb0880e-fd07-4a21-b3f2-15e4fb2a7609)

**Comment by jgunstone** [comment]
fixed by #8
