### ISSUE TITLE
🐛 Column with hardcoded key from test data

### ISSUE THREAD

**Issue by ollyhensby** [maxfordham/xlsxdatagrid#4]
**Issue**
I think this needs be made generic instead of using the `key` from the tests. Currently uses `a_int`.

https://github.com/maxfordham/xlsxdatagrid/blob/97148321dcbe8171ee2757466fe454061d505da3/src/xlsxdatagrid/xlsxdatagrid.py#L678-L680

**Comment by jgunstone** [comment]
good spot - deleted
